### ISSUE TITLE
Can't build playerctl because of missing auto-generated docs

### ISSUE THREAD

**Issue by ghost** [acrisci/playerctl#85]
I'm trying to build playerctl from scratch and have had a rough go at it. Not familiar with meson or ninja or automake... etcetera. So this has been somewhat of a nightmare, especially since the readme never specifies basic dependencies or how to generate certain objects or even how to do simple configuration options.

I've almost got it to build, I just can't seem to figure out how to get gtkdocize to generate the docs. The build pretty much fails there for me.

Here's what I'm doing.

```
git clone https://github.com/acrisci/playerctl.git
cd playerctl
./autogen.sh
```

autogen.sh gives a ton of output, but I narrowed it down to this block

```
checking for gtk-doc... yes
checking for gtkdoc-check... gtkdoc-check.test
checking for gtkdoc-check... /usr/bin/gtkdoc-check
checking for gtkdoc-rebase... /usr/bin/gtkdoc-rebase
checking for gtkdoc-mkpdf... /usr/bin/gtkdoc-mkpdf
checking whether to build gtk-doc documentation... no
checking for GTKDOC_DEPS... yes
checking that generated files are newer than configure... done
```

Which then led me to configure.ac. [In `configure.ac`, on line 59, I found this snippet which seems to refer to `gtkdocize`](https://github.com/acrisci/playerctl/blob/e01fbf6a84946076576038a4f4d3ecf49a87c5a4/configure.ac#L59). Which dictates it to not build a template. So I didn't think too much about it and ran along with it.

I ran meson and it gave me this output.

```
meson mesonbuild
The Meson build system
Version: 0.47.2
Source dir: /home/avery/Documents/github/playerctl
Build dir: /home/avery/Documents/github/playerctl/mesonbuild
Build type: native build
Project name: playerctl
Project version: 0.6.1
Native C compiler: cc (gcc 7.3.0 "cc (Ubuntu 7.3.0-16ubuntu3) 7.3.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Native dependency gobject-2.0 found: YES 2.56.2
Native dependency gio-unix-2.0 found: YES 2.56.2
Native dependency glib-2.0 found: YES 2.56.2
Configuring playerctl-version.h using configuration
Native dependency glib-2.0 found: YES 2.56.2
Native dependency gobject-introspection-1.0 found: YES 1.56.1
Native dependency gobject-introspection-1.0 found: YES 1.56.1
Configuring playerctl.1 using configuration
Program gtkdoc-scan found: YES (/usr/bin/gtkdoc-scan)
Dependency glib-2.0 found: YES (cached)
Configuring version.xml using configuration
Build targets in project: 8
Found ninja-1.8.2 at /usr/bin/ninja
```

Tbh, I didnt think much of it until I ran ninja. [Btw, you should really include stdio to get rid of those implicit warnings](https://github.com/acrisci/playerctl/blob/e01fbf6a84946076576038a4f4d3ecf49a87c5a4/playerctl/playerctl-cli.c#L191). It's a line at the head of the source. Simple enough of a fix. Anyways, here's the ninja output.

```
sudo ninja -C mesonbuild install
[sudo] password for avery: 
ninja: Entering directory `mesonbuild'
[3/12] Compiling C object 'playerctl/playerctl@@playerctl@exe/playerctl-cli.c.o'.
../playerctl/playerctl-cli.c: In function ‘position’:
../playerctl/playerctl-cli.c:191:5: warning: implicit declaration of function ‘printf’ [-Wimplicit-function-declaration]
     printf("%f\n", (double)offset / 1000000.0);
     ^~~~~~
../playerctl/playerctl-cli.c:191:5: warning: incompatible implicit declaration of built-in function ‘printf’
../playerctl/playerctl-cli.c:191:5: note: include ‘<stdio.h>’ or provide a declaration of ‘printf’
../playerctl/playerctl-cli.c: In function ‘status’:
../playerctl/playerctl-cli.c:242:3: warning: incompatible implicit declaration of built-in function ‘printf’
   printf("%s\n", state ? state : "Not available");
   ^~~~~~
../playerctl/playerctl-cli.c:242:3: note: include ‘<stdio.h>’ or provide a declaration of ‘printf’
../playerctl/playerctl-cli.c: In function ‘get_metadata’:
../playerctl/playerctl-cli.c:268:3: warning: incompatible implicit declaration of built-in function ‘printf’
   printf("%s", data);
   ^~~~~~
../playerctl/playerctl-cli.c:268:3: note: include ‘<stdio.h>’ or provide a declaration of ‘printf’
[10/12] Generating Playerctl-1.0.gir with a custom command.
g-ir-scanner: link: cc -o /home/avery/Documents/github/playerctl/mesonbuild/tmp-introspect_2av5j89/Playerctl-1.0 /home/avery/Documents/github/playerctl/mesonbuild/tmp-introspect_2av5j89/Playerctl-1.0.o -L. -Wl,-rpath,. -Wl,--no-as-needed -lplayerctl-1.0 -lgobject-2.0 -lglib-2.0 -lgio-2.0 -L/home/avery/Documents/github/playerctl/mesonbuild/playerctl -Wl,-rpath,/home/avery/Documents/github/playerctl/mesonbuild/playerctl -lgio-2.0 -lgobject-2.0 -Wl,--export-dynamic -lgmodule-2.0 -pthread -lglib-2.0
[11/12] Installing files.
Installing playerctl/libplayerctl-1.0.so.0.0.0 to /usr/local/lib/x86_64-linux-gnu
Installing playerctl/libplayerctl-1.0.a to /usr/local/lib/x86_64-linux-gnu
Installing playerctl/playerctl to /usr/local/bin
Installing playerctl/Playerctl-1.0.gir to /usr/local/share/gir-1.0
Installing playerctl/Playerctl-1.0.typelib to /usr/local/lib/x86_64-linux-gnu/girepository-1.0
Installing /home/avery/Documents/github/playerctl/playerctl/playerctl.h to /usr/local/include/playerctl
Installing /home/avery/Documents/github/playerctl/playerctl/playerctl-player.h to /usr/local/include/playerctl
Installing /home/avery/Documents/github/playerctl/mesonbuild/playerctl/playerctl-version.h to /usr/local/include/playerctl
Installing /home/avery/Documents/github/playerctl/mesonbuild/doc/playerctl.1 to /usr/local/share/man/man1
Installing /home/avery/Documents/github/playerctl/mesonbuild/meson-private/playerctl-1.0.pc to /usr/local/lib/x86_64-linux-gnu/pkgconfig
Running custom install script '/usr/bin/python3 /usr/local/bin/meson --internal gtkdoc --sourcedir=/home/avery/Documents/github/playerctl --builddir=/home/avery/Documents/github/playerctl/mesonbuild --subdir=doc/reference --headerdirs=/home/avery/Documents/github/playerctl/playerctl --mainfile=playerctl-docs.xml --modulename=playerctl --mode=auto --scanargs=--deprecated-guards="PLAYERCTL_DISABLE_DEPRECATED" --gobjects-types-file=/home/avery/Documents/github/playerctl/doc/reference/playerctl.types --fixxrefargs=--extra-dir=/usr/share/gtk-doc/html/gobject@@--extra-dir=/usr/share/gtk-doc/html/gio@@--extra-dir=/usr/share/gtk-doc/html --mkdbargs=--output-format=xml@@--name-space=meson.project_name() --content-files= --ignore-headers=playerctl.h@@playerctl-generated.h --cflags=-I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -pthread -I/usr/include/gio-unix-2.0/ --ldflags=-L/home/avery/Documents/github/playerctl/mesonbuild/playerctl -Wl,-rpath,/home/avery/Documents/github/playerctl/mesonbuild/playerctl -lplayerctl-1.0 -lglib-2.0 -lgobject-2.0 -lgio-2.0 --cc=cc --ld=cc'
Building documentation for playerctl
ERROR: 
Error in gtkdoc helper script:

ERROR: 'gtkdoc-scangobj' failed with status 1
Traceback (most recent call last):
  File "/usr/bin/gtkdoc-scangobj", line 71, in <module>
    sys.exit(scangobj.run(options))
  File "/usr/share/gtk-doc/python/gtkdoc/scangobj.py", line 1228, in run
    for line in common.open_text(options.types):
  File "/usr/share/gtk-doc/python/gtkdoc/common.py", line 57, in open_text
    return codecs.open(filename, mode, encoding=encoding)
  File "/usr/lib/python2.7/codecs.py", line 898, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: '/home/avery/Documents/github/playerctl/doc/reference/playerctl.types'

FAILED: meson-install 
/usr/bin/python3 /usr/local/bin/meson install --no-rebuild
ninja: build stopped: subcommand failed.
```

This keeps it from fully installing seeing as the shared object isn't available to the playerctl binary. I have no idea what to change to get it to build the required docs. 

Please help.

**Comment by hedning** [comment]
I'm running into the same issue. It looks like the `playerctl.types` file end up in `mesonbuild/doc/reference`, while the install script looks for it in the source directory, ie. `doc/reference`.

**Comment by acrisci** [comment]
Thanks for the report. Will work on making the build easier.

I think I fixed the gtk-doc issue with 686cbaa. Let me know if it works.

**Comment by acrisci** [comment]
Going to close this because the reporter is a ghost and I think I fixed it.

**Comment by hedning** [comment]
Yeah, that fixed it thanks :)
